# Generated by Django 4.2.4 on 2023-08-23 04:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0002_reminder_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perishable',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price'),
        ),
    ]
