# Generated by Django 4.2.4 on 2023-08-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0002_reminder_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='task_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
