# Generated by Django 4.2.4 on 2023-08-18 00:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('type', models.CharField(choices=[('D', 'Day'), ('E', 'Expiration'), ('G', 'Garbage')], default='D', max_length=1)),
                ('date', models.DateTimeField(verbose_name='Reminder Date')),
                ('remind_days_prio_by', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('remind_time', models.CharField(choices=[('M', 'Morning'), ('L', 'Noon'), ('A', 'Afternoon'), ('E', 'Evening'), ('N', 'Night')], default='M', max_length=1)),
                ('send_to_email', models.EmailField(max_length=70)),
                ('time_zone', models.CharField(choices=[('PT', 'Pacific Time'), ('MT', 'Mountain Time'), ('CT', 'Central Time'), ('ET', 'Eastern Time')], default='CT', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=30)),
                ('purchase_date', models.DateField(verbose_name='Purchase Date')),
                ('receipt_total', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total')),
                ('item_list', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('receipt_image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fridge_app.receipt')),
            ],
        ),
        migrations.CreateModel(
            name='Perishable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=0, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('store_name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('B', 'Bakery'), ('D', 'Dairy'), ('E', 'Eggs'), ('M', 'Meat and Seafood'), ('P', 'Produce'), ('O', 'Other')], default='P', max_length=2)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total')),
                ('expiration', models.DateField(verbose_name='Expiration Date')),
                ('receipt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fridge_app.receipt')),
                ('reminders', models.ManyToManyField(to='fridge_app.reminder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
