# Generated by Django 3.2.20 on 2023-08-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='time',
            field=models.TimeField(),
        ),
    ]
