# Generated by Django 4.2.4 on 2023-08-21 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='receipt_image',
        ),
    ]
