# Generated by Django 3.2.20 on 2023-08-18 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0002_auto_20230818_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='time',
        ),
    ]
