# Generated by Django 4.2.4 on 2023-08-21 23:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0002_remove_receipt_receipt_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='url',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
