# Generated by Django 4.2.4 on 2023-08-21 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0002_alter_receipt_receipt_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='receipt_image',
            new_name='receipt',
        ),
    ]
