# Generated by Django 4.2.4 on 2023-08-15 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0002_receipt_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['purchase_date']},
        ),
    ]
