# Generated by Django 3.2.20 on 2023-08-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0003_remove_reminder_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='time',
            field=models.TimeField(default='06:00'),
        ),
    ]
