# Generated by Django 4.2.4 on 2023-08-15 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0003_alter_receipt_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-purchase_date']},
        ),
    ]
