# Generated by Django 4.2.4 on 2023-08-21 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0003_rename_receipt_image_photo_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='receipt_image',
        ),
    ]
