# Generated by Django 4.2.4 on 2023-08-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0004_remove_receipt_receipt_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
