# Generated by Django 3.2.20 on 2023-08-16 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fridge_app', '0004_alter_receipt_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perishable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('store_name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('B', 'Bakery'), ('D', 'Dairy'), ('E', 'Eggs'), ('M', 'Meat and Seafood'), ('P', 'Produce'), ('O', 'Other')], default='P', max_length=2)),
                ('price', models.FloatField(verbose_name='Item Price')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
