# Generated by Django 3.2.20 on 2023-08-16 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0006_reminder_time_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='time_zone',
        ),
    ]
