# Generated by Django 3.2.20 on 2023-08-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0007_remove_reminder_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='time_zone',
            field=models.CharField(choices=[('PT', 'Pacific Time'), ('MT', 'Mountain Time'), ('CT', 'Central Time'), ('ET', 'Eastern Time')], default='CT', max_length=2),
        ),
    ]
