# Generated by Django 3.2.20 on 2023-08-16 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0008_reminder_time_zone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='Day(s) Prio',
            new_name='remind_days_prio_by',
        ),
    ]
