# Generated by Django 3.2.20 on 2023-08-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0009_rename_day(s) prio_reminder_remind_days_prio_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='name',
            field=models.CharField(default='name', max_length=30),
            preserve_default=False,
        ),
    ]
