# Generated by Django 4.2.4 on 2023-08-16 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0005_receipt_item_list_receipt_receipt_image'),
        ('fridge_app', '0010_reminder_name'),
    ]

    operations = [
    ]
