# Generated by Django 3.2.20 on 2023-08-16 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0006_perishable_expiration'),
        ('fridge_app', '0011_merge_20230816_2100'),
    ]

    operations = [
    ]
