# Generated by Django 4.2.4 on 2023-08-16 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0006_perishable_expiration'),
        ('fridge_app', '0011_merge_20230816_2147'),
    ]

    operations = [
    ]
