# Generated by Django 4.2.4 on 2023-08-16 22:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0013_remove_receipt_receipt_image_receipt_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='Image',
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total'),
        ),
    ]
