# Generated by Django 4.2.4 on 2023-08-16 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0012_merge_20230816_2200'),
        ('fridge_app', '0014_remove_receipt_image_receipt_receipt_image_and_more'),
    ]

    operations = [
    ]
