# Generated by Django 4.2.4 on 2023-08-16 23:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0016_alter_perishable_price_alter_reminder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perishable',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
