# Generated by Django 3.2.20 on 2023-08-17 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0017_perishable_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='perishable',
            name='receipt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fridge_app.receipt'),
        ),
        migrations.AddField(
            model_name='perishable',
            name='reminders',
            field=models.ManyToManyField(to='fridge_app.Reminder'),
        ),
    ]
