# Generated by Django 3.2.20 on 2023-08-17 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0011_merge_20230816_2209'),
        ('fridge_app', '0018_auto_20230817_1759'),
    ]

    operations = [
    ]
