# Generated by Django 4.2.4 on 2023-08-17 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0018_auto_20230817_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fridge_app.receipt')),
            ],
        ),
    ]
