# Generated by Django 3.2.20 on 2023-08-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0020_alter_perishable_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perishable',
            name='category',
            field=models.CharField(choices=[('Bakery', '🍞'), ('Dairy', '🥛'), ('Eggs', '🐔'), ('Meat and Seafood', '🍖'), ('Produce ', '\U0001f966'), ('Other', '🍕')], max_length=20),
        ),
    ]
