# Generated by Django 4.2.4 on 2023-08-17 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0020_remove_photo_receipt_alter_receipt_receipt_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ForeignKey(default='empty', on_delete=django.db.models.deletion.CASCADE, to='fridge_app.receipt'),
            preserve_default=False,
        ),
    ]
