# Generated by Django 3.2.20 on 2023-08-18 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0021_alter_perishable_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perishable',
            name='category',
            field=models.CharField(choices=[('B', 'Bakery 🍞'), ('D', 'Dairy 🥛'), ('E', 'Eggs 🐔'), ('M', 'Meat and Seafood 🍖'), ('P', 'Produce \U0001f966'), ('O', 'Other 🍕')], max_length=1),
        ),
    ]
