# Generated by Django 4.2.4 on 2023-08-17 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0021_photo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image',
        ),
    ]
