# Generated by Django 4.2.4 on 2023-08-17 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0022_remove_photo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='receipt_image',
        ),
        migrations.AddField(
            model_name='photo',
            name='receipt_image',
            field=models.OneToOneField(default='empty', on_delete=django.db.models.deletion.CASCADE, to='fridge_app.receipt'),
            preserve_default=False,
        ),
    ]
