# Generated by Django 4.2.4 on 2023-08-17 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0025_alter_photo_receipt_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='receipt_image',
            new_name='receipt_image2',
        ),
    ]
