# Generated by Django 4.2.4 on 2023-08-17 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0026_rename_receipt_image_photo_receipt_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='receipt_image2',
        ),
    ]
