# Generated by Django 4.2.4 on 2023-08-17 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_app', '0027_remove_photo_receipt_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='receipt_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fridge_app.receipt'),
        ),
    ]
